"""Manifest-driven batch loader for the remaining NPHC 2021 bulk CSVs.

The committed manifest is generated by ``scripts.census_bulk_manifest`` and
contains exact headers, source dimensions, published total codes, and permanent
indicator metadata. This loader does not infer metadata during ingestion.

Every file is isolated:

1. archive untouched bytes in the raw lake;
2. parse and validate the complete file without database writes;
3. run the quality gate on every candidate;
4. insert only new/changed cells in batches under one release;
5. commit that file, then continue.

Modes control storage volume without changing meanings:

``full``
    Every published cell (about 21.25 million across the current manifest).
``balanced``
    Every headline at every level, plus detailed breakdowns through district;
    municipality-level detailed cross-tabs are skipped.
``headline``
    Only all-dimension-total cells at every geography.

Blank source measures are logged and excluded, never converted to zero.

    make ingest-census-bulk-dry
    make ingest-census-bulk-balanced
    .venv/Scripts/python -m ingestion.nso.census_bulk --mode full
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import os
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Literal

import psycopg
from dotenv import load_dotenv

from ingestion.common.io_utf8 import configure_stdout_utf8
from ingestion.common.quality import Candidate, run_quality_gate
from ingestion.common.raw_lake import RawLake
from ingestion.nso.census_shape_a import GeographyMaps, load_geography_maps

DATASET_NAME = "National Population and Housing Census 2021"
MANIFEST_PATH = Path("reference/census/census_bulk_manifest.json")
CENSUS_YEAR = 2021
BATCH = 1000
QUALITY_BATCH = 10_000

Mode = Literal["full", "balanced", "headline"]


class BulkParseError(Exception):
    """A manifest/source mismatch that must block one file."""


@dataclass(frozen=True)
class IndicatorSpec:
    code: str
    unit_code: str
    measure: str
    split_values: dict[str, str]


@dataclass(frozen=True)
class SumRule:
    """A published identity the source must satisfy: total == sum(parts)."""

    total: str
    parts: tuple[str, ...]


@dataclass(frozen=True)
class FileSpec:
    stem: str
    source_csv: Path
    header_line: int
    header: tuple[str, ...]
    has_gapa: bool
    dimension_columns: tuple[str, ...]
    split_dimensions: tuple[str, ...]
    total_dimension_values: dict[str, str]
    label_columns: tuple[str, ...]
    measure_columns: tuple[str, ...]
    sum_rules: tuple[SumRule, ...]
    row_count: int
    indicator_specs: tuple[IndicatorSpec, ...]


@dataclass(frozen=True)
class ParsedCell:
    indicator_code: str
    geography_code: str
    geography_level: str
    breakdowns: dict[str, str]
    value: Decimal


@dataclass
class ParseStats:
    rows_seen: int = 0
    cells_emitted: int = 0
    blanks_skipped: int = 0
    institutional_rows_skipped: int = 0
    mode_cells_skipped: int = 0


@dataclass(frozen=True)
class DbRefs:
    dataset_id: int
    period_id: int
    indicators: dict[str, tuple[int, int, str]]
    geographies: dict[str, int]


def _scalar(cur: psycopg.Cursor[Any]) -> Any:
    row = cur.fetchone()
    return None if row is None else row[0]


def load_manifest(path: Path = MANIFEST_PATH) -> list[FileSpec]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("version") != 1 or not isinstance(payload.get("files"), list):
        raise BulkParseError(f"{path}: unsupported or malformed manifest")
    specs: list[FileSpec] = []
    for raw_file in payload["files"]:
        indicators = tuple(
            IndicatorSpec(
                code=raw["code"],
                unit_code=raw["unit_code"],
                measure=raw["measure"],
                split_values=dict(raw["split_values"]),
            )
            for raw in raw_file["indicator_specs"]
        )
        if "sum_rules" not in raw_file:
            raise BulkParseError(
                f"{raw_file['stem']}: manifest predates sum_rules; "
                "regenerate it with `make census-bulk-manifest`"
            )
        sum_rules = tuple(
            SumRule(total=raw["total"], parts=tuple(raw["parts"]))
            for raw in raw_file["sum_rules"]
        )
        specs.append(
            FileSpec(
                stem=raw_file["stem"],
                source_csv=Path(raw_file["source_csv"]),
                header_line=int(raw_file["header_line"]),
                header=tuple(raw_file["header"]),
                has_gapa=bool(raw_file["has_gapa"]),
                dimension_columns=tuple(raw_file["dimension_columns"]),
                split_dimensions=tuple(raw_file["split_dimensions"]),
                total_dimension_values=dict(raw_file["total_dimension_values"]),
                label_columns=tuple(raw_file["label_columns"]),
                measure_columns=tuple(raw_file["measure_columns"]),
                sum_rules=sum_rules,
                row_count=int(raw_file["row_count"]),
                indicator_specs=indicators,
            )
        )
    return specs


def _rows_from_payload(payload: bytes, spec: FileSpec) -> Iterator[dict[str, str]]:
    text = payload.decode("utf-8-sig")
    reader = csv.reader(io.StringIO(text, newline=""))
    for _ in range(spec.header_line - 1):
        next(reader, None)
    raw_header = next(reader, None)
    if raw_header is None:
        raise BulkParseError(f"{spec.stem}: header line {spec.header_line} is missing")
    header = [cell.strip() for cell in raw_header]
    while header and header[-1] == "":
        header.pop()
    if tuple(header) != spec.header:
        raise BulkParseError(
            f"{spec.stem}: source header changed; expected {list(spec.header)}, got {header}"
        )
    for line_number, raw_row in enumerate(reader, spec.header_line + 1):
        if not raw_row or not any(cell.strip() for cell in raw_row):
            continue
        row = raw_row[: len(header)]
        if len(row) != len(header):
            raise BulkParseError(
                f"{spec.stem} line {line_number}: width {len(row)} != {len(header)}"
            )
        yield dict(zip(header, row, strict=True))


def _map_geography(
    row: dict[str, str],
    spec: FileSpec,
    maps: GeographyMaps,
) -> tuple[str, str] | None:
    prov = row["prov"].strip()
    dist = row["dist"].strip()
    if prov == "0":
        return "NP", "country"
    if dist == "0":
        code = maps.provinces.get(prov)
        if code is None:
            raise BulkParseError(f"{spec.stem}: unmapped province code {prov}")
        return code, "province"
    if not spec.has_gapa:
        code = maps.districts.get(dist)
        if code is None:
            raise BulkParseError(f"{spec.stem}: unmapped district code {dist}")
        return code, "district"
    gapa = row["gapa"].strip()
    if gapa == "0":
        code = maps.districts.get(dist)
        if code is None:
            raise BulkParseError(f"{spec.stem}: unmapped district code {dist}")
        return code, "district"
    if gapa == "99":
        return None
    code = maps.local_units.get((dist, gapa))
    if code is None:
        raise BulkParseError(
            f"{spec.stem}: unmapped local unit dist={dist} gapa={gapa}"
        )
    return code, "local_unit"


def _breakdowns(row: dict[str, str], spec: FileSpec) -> dict[str, str]:
    regular_dimensions = [
        name
        for name in spec.dimension_columns
        if name not in spec.split_dimensions
    ]
    if all(
        row[dimension].strip() == spec.total_dimension_values[dimension]
        for dimension in regular_dimensions
    ):
        return {}

    breakdowns: dict[str, str] = {}
    if len(spec.dimension_columns) == len(spec.label_columns):
        labels_by_dimension = dict(
            zip(spec.dimension_columns, spec.label_columns, strict=True)
        )
    else:
        labels_by_dimension = {}

    for dimension in regular_dimensions:
        label_column = labels_by_dimension.get(dimension)
        label = row[label_column].strip() if label_column else ""
        code = row[dimension].strip()
        if label:
            breakdowns[dimension] = label
        elif code:
            breakdowns[dimension] = code
        else:
            breakdowns[dimension] = "(blank source code)"
    if not labels_by_dimension:
        for label_column in spec.label_columns:
            label = row[label_column].strip()
            if label:
                breakdowns[label_column] = label
    return breakdowns


def _indicator_lookup(spec: FileSpec) -> dict[tuple[str, tuple[tuple[str, str], ...]], str]:
    lookup: dict[tuple[str, tuple[tuple[str, str], ...]], str] = {}
    for indicator in spec.indicator_specs:
        key = (
            indicator.measure,
            tuple(sorted(indicator.split_values.items())),
        )
        if key in lookup:
            raise BulkParseError(f"{spec.stem}: duplicate manifest indicator key {key}")
        lookup[key] = indicator.code
    return lookup


def _parse_decimal(raw: str, context: str) -> Decimal | None:
    if raw.strip() == "":
        return None
    try:
        value = Decimal(raw)
    except InvalidOperation as exc:
        raise BulkParseError(f"{context}: non-numeric value {raw!r}") from exc
    if not value.is_finite():
        raise BulkParseError(f"{context}: non-finite value {raw!r}")
    if value < 0:
        raise BulkParseError(f"{context}: negative census count {value}")
    return value


def iter_cells(
    payload: bytes,
    spec: FileSpec,
    maps: GeographyMaps,
    mode: Mode,
    stats: ParseStats,
) -> Iterator[ParsedCell]:
    indicator_lookup = _indicator_lookup(spec)
    for row_number, row in enumerate(_rows_from_payload(payload, spec), 1):
        stats.rows_seen += 1
        mapped = _map_geography(row, spec, maps)
        if mapped is None:
            stats.institutional_rows_skipped += 1
            continue
        geography_code, geography_level = mapped
        breakdowns = _breakdowns(row, spec)

        for rule in spec.sum_rules:
            total = _parse_decimal(
                row[rule.total],
                f"{spec.stem} data row {row_number}:{rule.total}",
            )
            parts = [
                _parse_decimal(
                    row[part],
                    f"{spec.stem} data row {row_number}:{part}",
                )
                for part in rule.parts
            ]
            if total is not None and all(value is not None for value in parts):
                part_sum = sum(
                    (value for value in parts if value is not None),
                    Decimal(0),
                )
                if part_sum != total:
                    raise BulkParseError(
                        f"{spec.stem} data row {row_number}: "
                        f"{' + '.join(rule.parts)} = {part_sum} != "
                        f"{rule.total} {total}"
                    )

        split_key = tuple(
            sorted(
                (dimension, row[dimension].strip())
                for dimension in spec.split_dimensions
            )
        )
        for measure in spec.measure_columns:
            indicator_code = indicator_lookup.get((measure, split_key))
            if indicator_code is None:
                raise BulkParseError(
                    f"{spec.stem} data row {row_number}: no indicator for "
                    f"{measure}, split={dict(split_key)}"
                )
            value = _parse_decimal(
                row[measure],
                f"{spec.stem} data row {row_number}:{measure}",
            )
            if value is None:
                stats.blanks_skipped += 1
                continue
            if mode == "headline" and breakdowns:
                stats.mode_cells_skipped += 1
                continue
            if mode == "balanced" and geography_level == "local_unit" and breakdowns:
                stats.mode_cells_skipped += 1
                continue
            stats.cells_emitted += 1
            yield ParsedCell(
                indicator_code=indicator_code,
                geography_code=geography_code,
                geography_level=geography_level,
                breakdowns=dict(breakdowns),
                value=value,
            )


def _load_db_refs(cur: psycopg.Cursor[Any], specs: list[FileSpec]) -> DbRefs:
    cur.execute("SELECT id FROM datasets WHERE name_en = %s", (DATASET_NAME,))
    dataset_id = _scalar(cur)
    cur.execute(
        "SELECT id FROM time_periods WHERE period_type='year' AND gregorian_label=%s",
        (str(CENSUS_YEAR),),
    )
    period_id = _scalar(cur)
    codes = sorted(
        {
            indicator.code
            for spec in specs
            for indicator in spec.indicator_specs
        }
    )
    cur.execute(
        "SELECT i.code, i.id, i.unit_id, u.code "
        "FROM indicators i JOIN units u ON u.id=i.unit_id "
        "WHERE i.code = ANY(%s)",
        (codes,),
    )
    indicators = {
        code: (indicator_id, unit_id, unit_code)
        for code, indicator_id, unit_id, unit_code in cur.fetchall()
    }
    cur.execute("SELECT code, id FROM geographies")
    geographies = dict(cur.fetchall())
    if dataset_id is None or period_id is None:
        raise BulkParseError("census dataset/year reference missing; run make seed")
    missing = sorted(set(codes) - indicators.keys())
    if missing:
        raise BulkParseError(
            f"{len(missing)} bulk indicators not seeded (e.g. {missing[:3]}); "
            "run make seed-census"
        )
    return DbRefs(dataset_id, period_id, indicators, geographies)


def _validate_file(
    payload: bytes,
    spec: FileSpec,
    maps: GeographyMaps,
    refs: DbRefs,
    mode: Mode,
) -> ParseStats:
    stats = ParseStats()
    seen: set[tuple[int, int, str]] = set()
    candidates: list[Candidate] = []
    for cell in iter_cells(payload, spec, maps, mode, stats):
        indicator_id, unit_id, unit_code = refs.indicators[cell.indicator_code]
        geography_id = refs.geographies.get(cell.geography_code)
        if geography_id is None:
            raise BulkParseError(
                f"{spec.stem}: geography {cell.geography_code} is not seeded"
            )
        breakdown_key = json.dumps(
            cell.breakdowns,
            sort_keys=True,
            separators=(", ", ": "),
        )
        key = (indicator_id, geography_id, breakdown_key)
        if key in seen:
            raise BulkParseError(f"{spec.stem}: duplicate observation cell {key}")
        seen.add(key)
        candidates.append(
            Candidate(
                indicator_id=indicator_id,
                indicator_code=cell.indicator_code,
                unit_id=unit_id,
                unit_code=unit_code,
                period_id=refs.period_id,
                year=CENSUS_YEAR,
                value=cell.value,
            )
        )
        if len(candidates) >= QUALITY_BATCH:
            result = run_quality_gate(candidates)
            if not result.passed:
                raise BulkParseError("; ".join(result.failures[:5]))
            candidates.clear()
    if candidates:
        result = run_quality_gate(candidates)
        if not result.passed:
            raise BulkParseError("; ".join(result.failures[:5]))
    if stats.rows_seen != spec.row_count:
        raise BulkParseError(
            f"{spec.stem}: expected {spec.row_count} data rows, saw {stats.rows_seen}"
        )
    return stats


def breakdown_key(breakdowns: dict[str, str]) -> str:
    """Comparison key for a breakdowns mapping.

    Both sides of the change check must build their key here. ``breakdowns``
    is a jsonb column: Postgres stores keys in its own order (shortest first,
    then bytewise), which is not Python's insertion or alphabetical order, so
    comparing the rendered ``breakdowns::text`` never matches a multi-key
    mapping and every re-run reloads it. Sorting both sides fixes that.
    """
    return json.dumps(breakdowns, sort_keys=True, separators=(", ", ": "))


def _latest_values(
    cur: psycopg.Cursor[Any],
    spec: FileSpec,
    refs: DbRefs,
) -> dict[tuple[int, int, str], Decimal]:
    indicator_ids = [
        refs.indicators[indicator.code][0]
        for indicator in spec.indicator_specs
    ]
    cur.execute(
        "SELECT indicator_id, geography_id, breakdowns, value "
        "FROM observations WHERE is_latest AND time_period_id=%s "
        "AND indicator_id = ANY(%s)",
        (refs.period_id, indicator_ids),
    )
    return {
        (indicator_id, geography_id, breakdown_key(breakdowns or {})): value
        for indicator_id, geography_id, breakdowns, value in cur.fetchall()
    }


def _write_file(
    cur: psycopg.Cursor[Any],
    payload: bytes,
    spec: FileSpec,
    maps: GeographyMaps,
    refs: DbRefs,
    mode: Mode,
    raw_refs: list[str],
    stats: ParseStats,
) -> tuple[int, int, int]:
    cur.execute(
        "INSERT INTO ingestion_log (dataset_id, status) "
        "VALUES (%s, 'running') RETURNING id",
        (refs.dataset_id,),
    )
    log_id = _scalar(cur)
    cur.execute(
        "INSERT INTO releases (dataset_id, release_date) "
        "VALUES (%s, CURRENT_DATE) RETURNING id",
        (refs.dataset_id,),
    )
    release_id = _scalar(cur)
    latest = _latest_values(cur, spec, refs)

    loaded = unchanged = 0
    batch: list[tuple[Any, ...]] = []
    write_stats = ParseStats()
    for cell in iter_cells(payload, spec, maps, mode, write_stats):
        indicator_id, unit_id, _unit_code = refs.indicators[cell.indicator_code]
        geography_id = refs.geographies[cell.geography_code]
        key = breakdown_key(cell.breakdowns)
        if latest.get((indicator_id, geography_id, key)) == cell.value:
            unchanged += 1
            continue
        batch.append(
            (
                indicator_id,
                geography_id,
                refs.period_id,
                refs.dataset_id,
                release_id,
                cell.value,
                unit_id,
                json.dumps(cell.breakdowns),
            )
        )
        if len(batch) >= BATCH:
            cur.executemany(
                "INSERT INTO observations "
                "(indicator_id, geography_id, time_period_id, dataset_id, "
                "release_id, value, unit_id, breakdowns, status) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,'final')",
                batch,
            )
            loaded += len(batch)
            batch.clear()
    if batch:
        cur.executemany(
            "INSERT INTO observations "
            "(indicator_id, geography_id, time_period_id, dataset_id, "
            "release_id, value, unit_id, breakdowns, status) "
            "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,'final')",
            batch,
        )
        loaded += len(batch)

    cur.execute(
        "UPDATE releases SET raw_file_refs=%s, notes=%s WHERE id=%s",
        (
            json.dumps(raw_refs),
            f"bulk census file={spec.stem}; mode={mode}",
            release_id,
        ),
    )
    cur.execute(
        "UPDATE ingestion_log SET status='success', finished_at=now(), "
        "rows_in=%s, rows_loaded=%s, rows_rejected=%s, raw_file_refs=%s, "
        "release_id=%s, error_note=%s WHERE id=%s",
        (
            stats.cells_emitted + stats.blanks_skipped + stats.mode_cells_skipped,
            loaded,
            stats.blanks_skipped,
            json.dumps(raw_refs),
            release_id,
            (
                f"file={spec.stem}; mode={mode}; unchanged={unchanged}; "
                f"mode_skipped={stats.mode_cells_skipped}; "
                f"institutional_rows_skipped={stats.institutional_rows_skipped}"
            )[:1000],
            log_id,
        ),
    )
    return loaded, unchanged, release_id


def _record_failure(
    conn: psycopg.Connection[Any],
    dataset_id: int,
    spec: FileSpec,
    raw_refs: list[str],
    error: str,
) -> None:
    conn.rollback()
    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO ingestion_log "
            "(dataset_id,status,finished_at,rows_in,rows_loaded,rows_rejected,"
            "raw_file_refs,error_note) "
            "VALUES (%s,'failed',now(),0,0,0,%s,%s)",
            (
                dataset_id,
                json.dumps(raw_refs),
                f"file={spec.stem}; {error}"[:1000],
            ),
        )
    conn.commit()


def _select_specs(
    specs: list[FileSpec],
    requested: list[str],
    max_files: int | None,
) -> list[FileSpec]:
    if requested:
        wanted = {Path(value).stem.casefold() for value in requested}
        selected = [spec for spec in specs if spec.stem.casefold() in wanted]
        found = {spec.stem.casefold() for spec in selected}
        missing = sorted(wanted - found)
        if missing:
            raise BulkParseError(f"files not present in manifest: {missing}")
    else:
        selected = specs
    return selected[:max_files] if max_files is not None else selected


def run(
    mode: Mode,
    dry_run: bool,
    requested: list[str],
    max_files: int | None,
) -> int:
    configure_stdout_utf8()
    load_dotenv()
    specs = _select_specs(load_manifest(), requested, max_files)
    maps = load_geography_maps()
    db_url = os.environ.get("DATABASE_URL", "").strip()
    if not db_url:
        print("FAILURE: DATABASE_URL is empty. Fill in .env.")
        return 1

    conn = psycopg.connect(db_url, connect_timeout=30)
    with conn.cursor() as cur:
        refs = _load_db_refs(cur, specs)
    conn.commit()
    lake = None if dry_run else RawLake.from_env()

    total_cells = total_loaded = total_unchanged = 0
    failures: list[str] = []
    for number, spec in enumerate(specs, 1):
        print(f"[{number}/{len(specs)}] {spec.stem}")
        raw_refs: list[str] = []
        try:
            payload = spec.source_csv.read_bytes()
            if lake is not None:
                stored = lake.store(
                    f"nso/census2021/bulk/{spec.stem}",
                    payload,
                    f"file://{spec.source_csv}",
                    content_type="text/csv",
                    payload_filename=spec.source_csv.name,
                )
                raw_refs = [stored.payload_path]
            stats = _validate_file(payload, spec, maps, refs, mode)
            total_cells += stats.cells_emitted
            if dry_run:
                print(
                    f"  VALID: {stats.cells_emitted:,} cells; "
                    f"blank={stats.blanks_skipped:,}; "
                    f"mode-skipped={stats.mode_cells_skipped:,}"
                )
                continue
            with conn.cursor() as cur:
                loaded, unchanged, release_id = _write_file(
                    cur,
                    payload,
                    spec,
                    maps,
                    refs,
                    mode,
                    raw_refs,
                    stats,
                )
            conn.commit()
            total_loaded += loaded
            total_unchanged += unchanged
            print(
                f"  LOADED: {loaded:,}; unchanged={unchanged:,}; "
                f"release={release_id}"
            )
        except Exception as exc:  # noqa: BLE001 — isolate and report each file
            message = str(exc)
            failures.append(f"{spec.stem}: {message}")
            if not dry_run:
                _record_failure(conn, refs.dataset_id, spec, raw_refs, message)
            print(f"  FAILED: {message}")
    conn.close()

    print("Bulk census summary:")
    print(f"  files attempted : {len(specs)}")
    print(f"  files failed    : {len(failures)}")
    print(f"  cells validated : {total_cells:,}")
    if not dry_run:
        print(f"  loaded          : {total_loaded:,}")
        print(f"  unchanged       : {total_unchanged:,}")
    print(f"  mode            : {mode}")
    if failures:
        print("Failures (reported, not guessed):")
        for failure in failures:
            print(f"  - {failure}")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mode",
        choices=("full", "balanced", "headline"),
        default="balanced",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--file", action="append", default=[])
    parser.add_argument("--max-files", type=int)
    args = parser.parse_args()
    return run(args.mode, args.dry_run, args.file, args.max_files)


if __name__ == "__main__":
    sys.exit(main())
